-- MySQL Script generated by MySQL Workbench
-- Sun Oct  3 04:23:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema finaldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `finaldb` ;

-- -----------------------------------------------------
-- Schema finaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finaldb` DEFAULT CHARACTER SET utf8 ;
USE `finaldb` ;

-- -----------------------------------------------------
-- Table `finaldb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`user` (
                                             `idUser` INT NOT NULL AUTO_INCREMENT,
                                             `NickName` VARCHAR(45) NOT NULL,
                                             `Dateofbirth` VARCHAR(12) NOT NULL,
                                             `Gender` VARCHAR(45) NOT NULL,
                                             `Role` INT NOT NULL,
                                             `Password` VARCHAR(45) NOT NULL,
                                             UNIQUE INDEX `NickName_UNIQUE` (`NickName` ASC) VISIBLE,
                                             PRIMARY KEY (`idUser`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`session` (
                                                `idMovie` INT NOT NULL AUTO_INCREMENT,
                                                `PosterUrl` VARCHAR(100) NOT NULL,
                                                `FolderURL` VARCHAR(100) NOT NULL,
                                                `CountSeat` INT NOT NULL,
                                                `SessionDay` VARCHAR(12) NOT NULL,
                                                `Cost` INT NOT NULL,
                                                `TimeEnd` VARCHAR(45) NOT NULL,
                                                `TimeStart` VARCHAR(45) NOT NULL,
                                                `Status` VARCHAR(45) NOT NULL DEFAULT 'Open',
                                                PRIMARY KEY (`idMovie`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`order` (
                                              `idOrders` INT NOT NULL AUTO_INCREMENT,
                                              `MovieName` VARCHAR(45) NOT NULL,
                                              `Price` VARCHAR(45) NOT NULL,
                                              `OrderDate` VARCHAR(12) NOT NULL,
                                              `NumberOfSeat` INT NOT NULL,
                                              `TimeStart` VARCHAR(45) NOT NULL,
                                              `TimeEnd` VARCHAR(45) NOT NULL,
                                              `Day` VARCHAR(45) NOT NULL,
                                              `user_idUser` INT NOT NULL,
                                              `session_idMovie` INT NOT NULL,
                                              PRIMARY KEY (`idOrders`),
                                              INDEX `fk_order_user1_idx` (`user_idUser` ASC) VISIBLE,
                                              INDEX `fk_order_session1_idx` (`session_idMovie` ASC) VISIBLE,
                                              CONSTRAINT `fk_order_user1`
                                                  FOREIGN KEY (`user_idUser`)
                                                      REFERENCES `finaldb`.`user` (`idUser`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_order_session1`
                                                  FOREIGN KEY (`session_idMovie`)
                                                      REFERENCES `finaldb`.`session` (`idMovie`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`filmDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`filmDetail` (
                                                   `idfilmDetail` INT NOT NULL AUTO_INCREMENT,
                                                   `Name` VARCHAR(100) NOT NULL DEFAULT 'Cancelled',
                                                   `Description` VARCHAR(2000) NOT NULL DEFAULT 'Cancelled',
                                                   `Actor` VARCHAR(100) NOT NULL DEFAULT 'Cancelled',
                                                   `Director` VARCHAR(100) NOT NULL DEFAULT 'Cancelled',
                                                   `session_idMovie` INT NOT NULL,
                                                   PRIMARY KEY (`idfilmDetail`),
                                                   INDEX `fk_filmDetail_session1_idx` (`session_idMovie` ASC) VISIBLE,
                                                   CONSTRAINT `fk_filmDetail_session1`
                                                       FOREIGN KEY (`session_idMovie`)
                                                           REFERENCES `finaldb`.`session` (`idMovie`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`language` (
                                                 `idLanguage` INT NOT NULL AUTO_INCREMENT,
                                                 `Name` VARCHAR(100) NOT NULL,
                                                 `Description` VARCHAR(2000) NOT NULL,
                                                 `filmDetail_idfilmDetail` INT NULL,
                                                 PRIMARY KEY (`idLanguage`),
                                                 INDEX `fk_language_filmDetail1_idx` (`filmDetail_idfilmDetail` ASC) VISIBLE,
                                                 CONSTRAINT `fk_language_filmDetail1`
                                                     FOREIGN KEY (`filmDetail_idfilmDetail`)
                                                         REFERENCES `finaldb`.`filmDetail` (`idfilmDetail`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- we don't know how to generate root <with-no-name> (class Root) :(
create table session
(
    idMovie int auto_increment
        primary key,
    PosterUrl varchar(100) not null,
    FolderURL varchar(100) not null,
    CountSeat int not null,
    SessionDay varchar(12) not null,
    Cost int not null,
    TimeEnd varchar(45) not null,
    TimeStart varchar(45) not null,
    Status varchar(45) default 'Open' not null
);

create table filmdetail
(
    idfilmDetail int auto_increment
        primary key,
    Name varchar(100) default 'Cancelled' not null,
    Description varchar(2000) default 'Cancelled' not null,
    Actor varchar(100) default 'Cancelled' not null,
    Director varchar(100) default 'Cancelled' not null,
    session_idMovie int not null,
    constraint fk_filmDetail_session1
        foreign key (session_idMovie) references session (idMovie)
);

create index fk_filmDetail_session1_idx
    on filmdetail (session_idMovie);

create table language
(
    idLanguage int auto_increment
        primary key,
    Name varchar(100) not null,
    Description varchar(2000) not null,
    filmDetail_idfilmDetail int null,
    constraint fk_language_filmDetail1
        foreign key (filmDetail_idfilmDetail) references filmdetail (idfilmDetail)
);

create index fk_language_filmDetail1_idx
    on language (filmDetail_idfilmDetail);

create table user
(
    idUser int auto_increment
        primary key,
    NickName varchar(45) not null,
    Dateofbirth varchar(12) not null,
    Gender varchar(45) not null,
    Role int not null,
    Password varchar(45) not null,
    constraint NickName_UNIQUE
        unique (NickName)
);

create table `order`
(
    idOrders int auto_increment
        primary key,
    MovieName varchar(45) not null,
    Price varchar(45) not null,
    OrderDate varchar(12) not null,
    NumberOfSeat int not null,
    TimeStart varchar(45) not null,
    TimeEnd varchar(45) not null,
    Day varchar(45) not null,
    user_idUser int not null,
    session_idMovie int not null,
    constraint fk_order_session1
        foreign key (session_idMovie) references session (idMovie),
    constraint fk_order_user1
        foreign key (user_idUser) references user (idUser)
);

create index fk_order_session1_idx
    on `order` (session_idMovie);

create index fk_order_user1_idx
    on `order` (user_idUser);


